version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_NAME:-correodb}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-correodb}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      SERVER_PORT: ${USER_SERVICE_PORT:-8081}
    ports:
      - "${USER_SERVICE_PORT:-8081}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  shipping-service:
    build: 
      context: ./shipping-service
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-correodb}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      SERVER_PORT: ${SHIPPING_SERVICE_PORT:-8082}
    ports:
      - "${SHIPPING_SERVICE_PORT:-8082}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      user-service:
        condition: service_healthy
      shipping-service:
        condition: service_healthy
    environment:
      SERVER_PORT: ${API_GATEWAY_PORT:-8080}
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres-data:
