server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: shipping-service
          uri: http://shipping-service:8082
          predicates:
            - Path=/api/shipments/** 